---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.7-stretch

inputs:
  - name: bpm-mail-lambda
  - name: role

outputs:
  - name: generated

run:
  path: bpm-mail-lambda/ci/tasks/bpm-mail-lambda.sh
